services:
  bible_frontend:
    container_name: bible_frontend
    image: node:24.12.0
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - bible_network

networks:
  bible_network: